defmodule BuscaLivro.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:books), :platform_id, to: :image_url

    alter table(:books) do
      remove :description
    end

    drop constraint(:books, "books_platform_id_fkey")

    alter table(:books) do
      modify :image_url, :text
    end
  end

  def down do
    alter table(:books) do
      modify :image_url,
             references(:plataforms,
               column: :id,
               name: "books_platform_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:books) do
      add :description, :text, null: false
    end

    rename table(:books), :image_url, to: :platform_id
  end
end
