defmodule BuscaLivro.Repo.Migrations.MigrateResources7 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :wanted_words, {:array, :text}, null: false, default: []
    end
  end

  def down do
    alter table(:users) do
      modify :wanted_words, {:array, :text}, null: true, default: nil
    end
  end
end
