defmodule BuscaLivro.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:books) do
      add :url, :text, null: false
    end

    create unique_index(:books, [:image_url], name: "books_unique_url_index")
  end

  def down do
    drop_if_exists unique_index(:books, [:image_url], name: "books_unique_url_index")

    alter table(:books) do
      remove :url
    end
  end
end
