defmodule BuscaLivro.Repo.Migrations.MigrateResources4 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:books, [:image_url], name: "books_unique_url_index")

    create unique_index(:books, [:url], name: "books_unique_url_index")
  end

  def down do
    drop_if_exists unique_index(:books, [:url], name: "books_unique_url_index")

    create unique_index(:books, [:image_url], name: "books_unique_url_index")
  end
end
