defmodule BuscaLivro.Repo.Migrations.MigrateResources6 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :wanted_words, {:array, :text}
    end
  end

  def down do
    alter table(:users) do
      remove :wanted_words
    end
  end
end
