defmodule BuscaLivro.Repo.Migrations.MigrateResources5 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:book_users, primary_key: false) do
      add :book_id,
          references(:books,
            column: :id,
            name: "book_users_book_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :user_id,
          references(:users,
            column: :id,
            name: "book_users_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:book_users, "book_users_book_id_fkey")

    drop constraint(:book_users, "book_users_user_id_fkey")

    drop table(:book_users)
  end
end
