defmodule BuscaLivro.Repo.Migrations.MigrateResources8 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:book_users, [:book_id, :user_id],
             name: "book_users_unique_found_book_index"
           )
  end

  def down do
    drop_if_exists unique_index(:book_users, [:book_id, :user_id],
                     name: "book_users_unique_found_book_index"
                   )
  end
end
